---
- include: mysql_root_pw.yml

- name: CentOS 8 | set MariaDB repository link
  set_fact:
    mariadb_repo_url: http://yum.mariadb.org/10.5/centos8-amd64

- name: Add MariaDB Repository
  yum_repository:
    name: MariaDB
    description: Official MariaDB Repository
    baseurl: "{{ mariadb_repo_url }}"
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB

- name: redhat | installing pre-reqs
  yum:
    name:
      - "python3-mysql"
      - "socat"
    state: "present"
    update_cache: yes
  become: true
  when: >
    ansible_distribution != "Fedora"

- name: Precreate /etc/my.cnf.d in case we need to add mariadb_config_overrides file
  file:
    path: /etc/my.cnf.d
    state: directory
    mode: 0755
    recurse: yes
  become: true
  changed_when: false
  when: mariadb_config_overrides is defined

- name: redhat | add an overrides file
  template:
    src: "etc/mariadb_overrides.cnf.j2"
    dest: "/etc/my.cnf.d/overrides.cnf"
    owner: "root"
    group: "root"
    mode: 0644
  become: true
  when: mariadb_config_overrides is defined

- name: redhat | installing mariadb mysql
  yum:
    name:
      - "MariaDB-server"
      - "galera"
    state: "present"
  become: true
  when: >
    ansible_distribution != "Fedora"

- name: redhat | installing mariadb mysql
  dnf:
    name:
      - "MariaDB-server"
      - "galera"
      - "python3-mysql"
    state: present
  become: true
  when: >
    ansible_distribution == "Fedora"

- name: Remove migrated-from-my.cnf-settings.conf that is causing MariaDB to not start
  file:
    path: /etc/systemd/system/mariadb.service.d/migrated-from-my.cnf-settings.conf
    state: absent
  become: true

- name: reload systemd for MariaDB changes
  become: true
  systemd:
    daemon_reload: true

- name: redhat | ensuring mariadb mysql is enabled on boot and started
  service:
    name: "mariadb"
    state: "started"
    enabled: yes
  become: true
